### ISSUE TITLE
Install only webinterface

### ISSUE THREAD

**Issue by kroerig** [ngrie/rtmpie#13]
Hello,

I already have a running NGINX RTMP and MariaDB server. How can I install the webinterface only?

**Comment by ngrie** [comment]
The docker setup exists because a manual setup of all necessary components would be a complex and error-prone thing to do, especially for inexperienced users. Because of this, there is no official installation method apart from the provided docker setup.

Of course it is possible nevertheless. One would need to build the frontend assets using webpack, install the PHP application using composer, run the "mercure hub" to make realtime updates work, and then tie everything together in the NGINX and application configuration files.
